[package]
name = "generator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bempline = { path = "../../bempline" }
confindent = "2.0.1"
parser = { path = "../parser" }
thiserror = "1.0"